version: "3"

networks:
  app-tier:
    driver: bridge

services:
  jupyter:
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    links:
      - mysql
    networks:
      - app-tier
    volumes:
      - "./notebooks:/notebooks"
      - "./data:/data"

  mongodb:
    image: 'bitnami/mongodb:latest'
    networks:
      - app-tier

  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: data
      MYSQL_USER: data	
      MYSQL_DATABASE: meteo
    networks:
      - app-tier
         	